#!/bin/bash
# Takes an input file extension and changes all files to another extension.

info_string="For more info, use chext --help"

# Set argument defaults
current=''
new=''
dir=.
all_flag=false
strip_flag=false

if (( $#==0 )) || [[ "$1" =~ ^((-h)|(--help))$ ]]; then
    echo "chext: Changes all files of one extension to another."
    echo "Usage: chext [-d dir] [in|-a] [out|-s]"
    echo "  -d: set the directory to change file extensions, defaults to ."
    echo "  -a: changes the extension for all files"
    echo "  -s: removes file extensions"
    exit 1
fi

# Handle each arg
while (( $# )); do
	if [[ "$1" =~ ^((-d)|(--directory))$ ]]; then
		shift
        if [[ -d $1 ]]; then
            dir=$1
        else
            echo "Invalid directory given"
            echo $info_string
            exit 1
        fi
    elif [[ "$1" =~ ^((-a)|(--all))$ ]]; then
        all_flag=true
    elif [[ "$1" =~ ^((-s)|(--strip))$ ]]; then
        strip_flag=true
	elif [[ $current = '' ]] && [[ $all_flag = false ]]; then
		current="$1"
	elif [[ $new = '' ]] && [[ $strip_flag = false ]]; then
		new=".$1"
	fi
    shift
done

# Handle too few args
if [[ $current = '' ]] && [[ $all_flag = false ]]; then
    echo "Please give an input file extension, or use -a to select all."
    echo $info_string
    exit 1
elif [[ $new = '' ]] && [[ $strip_flag = false ]]; then
    echo "Please enter an output file extension, or use -s to remove extensions."
    echo $info_string
    exit 1
fi

# Move to target directory, rename each file, and move back
cd $dir

if [[ $all_flag ]]; then
    for file in *; do
        mv "$file" "${file%.*}$new" 
    done
else
    for file in *.$current; do
        mv "$file" "${file%.$current}$new"
    done
fi

cd - > /dev/null

