#!/bin/bash
# Takes an input file extension and changes all files to another extension.

# Set argument defaults
current=''
new=''
dir=.
dir_flag=false
all_flag=false
strip_flag=false

#Handle each arg
for arg in "$@"; do
	if [[ $dir_flag = true ]]; then
		dir=$arg
		dir_flag=false
	elif [[ "$arg" =~ ^((-d)|(--directory)) ]]; then
		dir_flag=true
    elif [[ "$arg" =~ ^((-a)|(--all)) ]]; then
        all_flag=true
    elif [[ "$arg" =~ ^((-s)|(--strip)) ]]; then
        strip_flag=true
	elif [[ $current = '' ]] && [[ $all_flag = false ]]; then
		current=$arg
	elif [[ $new = '' ]] && [[ $strip_flag = false ]]; then
		new=".$arg"
	fi
done

if [[ $current = '' ]] && [[ $all_flag = false ]]; then
    echo "Please give an input file extension, or use -a to select all."
    echo "For more info use chext --help"
    exit 1
fi

if [[ $new = '' ]] && [[ $strip_flag = false ]]; then
    echo "Please enter an output file extension, or use -s to remove extensions."
    echo "For more info use chext --help"
    exit 1
fi

cd $dir

# Rename each file in the directory with the extension
if [[ $all_flag ]]; then
    for file in *; do
        mv "$file" "${file%.*}$new" 
    done
else
    for file in *.$current; do
        mv "$file" "${file%.$current}$new"
    done
fi

cd - > /dev/null

