#!/bin/bash

# Make the waste directory in the users home directory if it does not exist.
mkdir -p ~/.waste

# Test if we are attempting to delete a directory and error.
if [ -d $1 ]
then echo "del: cannot delete $1: Is a directory."
	exit 1
else mv $1 ~/.waste
fi

