#!/bin/bash

# Setup variables to be used in the final command.
COMMAND="head"
COUNT=10
DIRECTORY=.
FILES=""

# For each passed argument, change the relevant variable.
while (( $# )); do
	# Choose head or tail with -h, -t, --head, or --tail.
	if [[ "$1" = "-t" ]] || [[ "$1" = "--tail" ]]; then
		COMMAND="tail"
        shift
        COUNT="$1"
	elif [[ "$1" = "-h" ]] || [[ "$1" = "--head" ]]; then
		COMMAND="head"
        shift
        COUNT="$1"
	# If the argument was a directory, use it as the default.
	elif [[ -d $arg ]]; then
		DIRECTORY=$arg
	fi
    shift
done

# Get all non-directory files from the given directory.
for file in $DIRECTORY/*; do
	if [[ ! -d $file ]]; then
		FILES="$FILES $file"
	fi
done

# Run either head or tail, for the given number of lines, with the list of files as the argument.
$COMMAND -n$COUNT $FILES

